### ISSUE TITLE
Work with Octave too?

### ISSUE THREAD

**Issue by PallHaraldsson** [SciML/MATLABDiffEq.jl#21]
Was there some other point with this package than to show Julia faster? I mean if MATLAB has some more functionality you can use, and possibly even Octave too, then it's good to know you can call it from Julia easily (through Python, using Oct2Py), as I tried the other day. I doubt their to be faster.

I have no need for ODE/this or related packages, was just curious how it worked, if it uses a toolbox, or same would be available in Octave. Maybe it is despite the error I got here (did I do something wrong?):

https://uk.mathworks.com/help/matlab/math/choose-an-ode-solver.html

```
>> [t,yv] = ode45(@imaginaryODE, tspan, yv0);
error: 'complexf' undefined near line 6 column 6
error: called from
    imaginaryODE at line 6 column 4
    starting_stepsize at line 46 column 5
    ode45 at line 192 column 25
```

**Comment by ChrisRackauckas** [comment]
MATLAB and Octave have less functionality, so it's kind of just there for research and to compare methods. If you want  to setup calls into Octave, sure, but there's also LSODA.jl which would be more direct to the same method.

**Comment by ChrisRackauckas** [comment]
Are you trying to translate something with complex numbers? That might not work so well.

**Comment by PallHaraldsson** [comment]
Do I was just trying o copy-past some code at MATLAB's website to see if it worked in Octave (if, something you might want enabled here). There was a function definition there, but it didn't end in `end` so at least that was missing. I don't have a working MATLAB any more so I couldn't test there to see if I had correct code.
